version: '3.8'

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
    container_name: postgresContainer

  db2:
    image: mysql:8
    ports:
      - "3307:3307"
    environment:
      MYSQL_USER: mysql
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: blog
    container_name: mysqlContainer

